import React from 'react';
import { ShieldAlert } from 'lucide-react';

export const DisclaimerBanner: React.FC = () => {
  return (
    <div className="w-full bg-slate-900/90 border-b border-amber-500/30 py-2.5 px-4 text-xs text-amber-300 flex items-center justify-center gap-2 text-center backdrop-blur-md">
      <ShieldAlert className="w-4 h-4 text-amber-400 shrink-0" />
      <span>
        <strong>Notice (E5):</strong> Verdicts generated by StillHere AI Jury are advisory assessments, not legal determinations. Do not rely on them as sole proof. If you suspect active fraud, contact IC3.gov or local law enforcement.
      </span>
    </div>
  );
};
